MMS/MusicMatchSpotifyWeb/Controllers/HomeController.cs
using MusicMatchSpotifyWeb.ViewModel;
using SpotifyWebAPI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MusicMatchSpotifyWeb.Controllers
{
    public class HomeController : Base
    {
        const string clientId = "d2982c5e5488466bb1b10dc77648fe81";
        const string clientSecret = "597fe6cf0d604935928deca66d73c557";
        //const string redirectUri = "http://localhost:26120/Home/Callback";
        const string redirectUri = "http://mmspotify.azurewebsites.net/Home/Callback";
        

        // GET: /Home/
        public ActionResult Index()
        {
            Authentication.ClientId = clientId;
            Authentication.ClientSecret = clientSecret;
            Authentication.RedirectUri = redirectUri;

            StringBuilder strAuthorizePath = new StringBuilder();

            strAuthorizePath.Append("https://accounts.spotify.com/authorize/?");
            strAuthorizePath.Append("client_id=").Append(clientId);
            strAuthorizePath.Append("&response_type=code");
            strAuthorizePath.Append("&redirect_uri=").Append(redirectUri);
            strAuthorizePath.Append("&scope=").Append(string.Empty);

            return Redirect(strAuthorizePath.ToString());
        }

        public async Task<ActionResult> Callback()
        {
            if (AuthenticationToken.HasExpired)
                AuthenticationToken = await SpotifyWebAPI.Authentication.GetAccessToken(Request.QueryString["code"]);

            LoggedUser = await SpotifyWebAPI.User.GetCurrentUserProfile(AuthenticationToken);

            ViewData["LoggedUser"] = LoggedUser;

            var usersPlaylist = await SpotifyWebAPI.Playlist.GetUsersPlaylists(LoggedUser, AuthenticationToken);

            List<PlaylistViewModel> pvm = new List<PlaylistViewModel>();

            if (usersPlaylist.Items.Count() > 0)
            {
                usersPlaylist.Items.ForEach(w => pvm.Add(new PlaylistViewModel()
                {
                    Id = w.Id,
                    Description = w.Description,
                    Images = w.Images,
                    Name = w.Name,
                    Owner = w.Owner
                }));
            }
            return View(pvm);
        }

        public PartialViewResult Action()
        {
            return PartialView("~/Views/Shared/_MenuLogoHeader.cshtml", LoggedUser);
        }

        public async Task<ViewResult> Profile()
        { 
            ViewData["Following"] = await SpotifyWebAPI.User.GetFollowedArtists(AuthenticationToken);
            return View(LoggedUser);
        }
    }
}

MMS/MusicMatchSpotifyWeb/Controllers/PlaylistTracksController.cs
using MusicMatchSpotifyWeb.ViewModel;
using SpotifyWebAPI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MusicMatchSpotifyWeb.Controllers
{
    public class PlaylistTracksController : Base
    {
        private int _offset = 100;

        //
        // GET: /PlaylistTracks/
        public async Task<ActionResult> Index(string playlistId, string ownerId)
        {
            Session["NextUrl"] = null;

            var playlistTracks = await SpotifyWebAPI.Playlist.GetPlaylistTracks(ownerId, playlistId, AuthenticationToken);
            var currentPlaylist = await SpotifyWebAPI.Playlist.GetPlaylist(ownerId, playlistId, AuthenticationToken);
            var usersPlaylist = await SpotifyWebAPI.Playlist.GetUsersPlaylists(LoggedUser.Id, AuthenticationToken);

            PlaylistTracksViewModel playlistTracksVM = new PlaylistTracksViewModel()
            {
                Playlist = usersPlaylist,
                PlaylistTrack = playlistTracks,
                CurrentPlaylist = currentPlaylist
            };
            ViewData["LoggedUser"] = LoggedUser;
            return View(playlistTracksVM);
        }

        public async Task<PartialViewResult> PlaylistTracks(string nextUrl)
        {
            Page<PlaylistTrack> playlistTracks = new Page<PlaylistTrack>();

            if (nextUrl != null)
            {
                if (Session["NextUrl"] == null)
                {
                    playlistTracks = await SpotifyWebAPI.Playlist.GetPlaylistTracks(nextUrl, AuthenticationToken);
                }
                else
                {
                    if (Session["NextUrl"].ToString() == "noRows") { return PartialView(playlistTracks); }
                    playlistTracks = await SpotifyWebAPI.Playlist.GetPlaylistTracks(Session["NextUrl"].ToString(), AuthenticationToken);

                }

                Session["NextUrl"] = playlistTracks.Next != null ? playlistTracks.Next : "noRows";
            }
            return PartialView(playlistTracks);
        }

    }
}

MMS/MusicMatchSpotifyWeb/Views/Home/Callback.cshtml
@model IEnumerable<MusicMatchSpotifyWeb.ViewModel.PlaylistViewModel>

@{
    ViewBag.Title = "Callback";
}

@{ var user = ViewData["LoggedUser"] as SpotifyWebAPI.User; }

@section header{ @{Html.RenderPartial("_LogoHeader", @user);} }

<style>
    body{ margin-top:20px;}
</style>

<div class="container">
    <!-- Jumbotron Header -->
    <header class="jumbotron hero-spacer">
        <h1>Bem Vindo @user.DisplayName!</h1>
        <p>Aqui você poderá ver sua playlist, do seus amigos, comparar quais músicas vocês possuem em comum, e muito mais! Confira!</p>
        <p>
            <a class="btn btn-primary btn-large">Saiba Mais!</a>
        </p>
    </header>
    <hr>
    <!-- Title -->
    <div class="row">
        <div class="col-lg-12">
            <h3>Minhas Playlists</h3>
        </div>
    </div>
    <!-- /.row -->
    <!-- Page Features -->
    <div class="row text-center">
        @foreach (var item in @Model)
    {
    <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
            <img src="@item.Images.FirstOrDefault().Url" alt="">
            <div class="caption">
                <h3>@item.Name</h3>
                <p>Criada por: @item.Owner.Id</p>
                <p>
                    <a href="#" class="btn btn-primary">Comparar</a> @Html.ActionLink("Ver músicas", "Index", "PlaylistTracks", new { playlistId = @item.Id, ownerId= @item.Owner.Id }, new { @class = "btn btn-default" })
                </p>
            </div>
        </div>
    </div>
    }
    </div>
    <!-- /.row -->
</div>

MMS/MusicMatchSpotifyWeb/Views/Home/Profile.cshtml
@model SpotifyWebAPI.User
@section header{ @{Html.RenderPartial("_LogoHeader", @Model);} }
@{ SpotifyWebAPI.Page<SpotifyWebAPI.Artist> following = ViewData["Following"] as SpotifyWebAPI.Page<SpotifyWebAPI.Artist>;}
<style>
    body {
        margin-top: 0px;
    }

    .teste {
        background-image: url("https://i.scdn.co/image/69e330eac7fe4c7a7cd15fc55f62ad998d86524b");
        background-repeat: no-repeat;
        background-size: 140%;
        opacity: 0.2;
        background-position: center;
        background-size: cover;
    }
</style>
<header class="profile-header-image">
    <div class="headline">
        <div class="container">
            <h2>Spotify</h2>
            <h2>meu perfil</h2>
        </div>
    </div>
</header>
<div class="container">

    <div class="featurette" id="about">
        <div class="row">
            <div class="col-md-6" style="margin-top:20px">
                <dl class="dl-horizontal profile-perfil-usuario">
                    <dt>Nome :</dt>
                    <dd>@Model.DisplayName</dd>
                    <dt>Email :</dt>
                    <dd>@Model.EmailAddress</dd>
                    <dt>País :</dt>
                    <dd>@Model.Country</dd>
                    <dt>Conta :</dt>
                    <dd>@Model.Product</dd>
                    <dt>Usuário :</dt>
                    <dd>@Model.Id</dd>
                </dl>
            </div>
            <div class="col-md-6" style="margin-top:20px">
                <img class="featurette-image img-circle img-responsive pull-right" src="@Url.Content(@Model.Images[0].Url)">
            </div>
        </div>
        <div class="container">
            <ul class="nav nav-tabs" style="margin-top: 10px; border-bottom: 1px solid #e4e4e4; width: 100%">
                <li class="active"><a href="#">Following (@following.Items.Count)</a></li>
                <li><a href="#">Follower (0)</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="container-fluid">
                        @foreach (var item in @following.Items)
                        {
                            <div class="row voffset2">
                                <div class="col-md-2">
                                    <div class="img-circle" style="height:130px; width:130px;overflow:hidden;">
                                        <img class="portrait" src="@item.Images[0].Url" alt="Alternate Text" />
                                    </div>
                                </div>
                                <div class="col-md-2" style="margin-top:64px;">
                                    <p class="text-left menu-font-size">@item.Name</p>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MMS/MusicMatchSpotifyWeb/Views/PlaylistTracks/Index.cshtml
@model MusicMatchSpotifyWeb.ViewModel.PlaylistTracksViewModel
@{
    ViewBag.Title = "Index";
}

@{ var user = ViewData["LoggedUser"] as SpotifyWebAPI.User; }

@section header{ 
                    @{Html.RenderPartial("_LogoHeader", @user);} 
               }
<style>
    .table-hover > tbody > tr:hover {
        background-color: #97b8d3;
    }

    .sort-duration {
        width: 88px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p class="lead">@Model.CurrentPlaylist.Name</p>
            <div class="list-group">
                @foreach (var item in @Model.Playlist.Items.OrderBy(w => w.Name))
                {
                    var css = new object();

                    if (@Model.CurrentPlaylist.Id == item.Id)
                    {
                        css = new { @class = "list-group-item active" };
                    }
                    else
                    {
                        css = new { @class = "list-group-item" };
                    }

                    @Html.ActionLink(item.Name, "Index", "PlaylistTracks", new { playlistId = item.Id, ownerId = item.Owner.Id }, css)
                }
            </div>
        </div>
        <div class="col-md-9">
            <div class="thumbnail">
                <div class="row">
                    <div class="col-md-3">
                        <img class="plt-imgPlaylistTracks" src='@Url.Content(@Model.CurrentPlaylist.Images.FirstOrDefault().Url)' width="210" height="210" alt="">
                    </div>
                    <div class="col-md-9">
                        <h5>PLAYLIST</h5>
                    </div>
                    <div class="col-xs-6">
                        <h2>@Model.CurrentPlaylist.Name</h2>
                    </div>
                    <div class="plt-duracao">
                        @{
                            int duracaoMS = 0;
                            foreach (var item in @Model.CurrentPlaylist.Tracks.Items)
                            {
                                duracaoMS += item.Track.Duration;
                            }

                            TimeSpan time = TimeSpan.FromMilliseconds(duracaoMS);
                            string resposta = string.Format("{0:D2} hs {1:D2} min",
                                                                    time.Hours,
                                                                    time.Minutes);
                            string qtdMusicas = string.Format("{0} Músicas, ", Model.CurrentPlaylist.Tracks.Items.Count.ToString());

                            @qtdMusicas @resposta
                        }
                    </div>
                    <div class="plt-seguidores">
                        <p class="pull-right">@Model.CurrentPlaylist.Followers.Total Seguidores</p>
                    </div>
                </div>
            </div>
            <div class="well">
                <div class="row">
                    <div class="col-md-2 text-left">
                        <a class="btn btn-success" for="collapseExample" data-toggle="collapse" href="#collapseExample" aria-expanded="true" aria-controls="collapseExample">Pesquisar Música</a>
                    </div>
                    <div id="collapseExample" class="col-md-3 collapse width plt-div-comparar-playlist" aria-expanded="false">
                        <div style="background-color: white; padding:2px; width:247px ">
                            <input id="search-navigation" class="form-control" data-list=".navigation_list" style="width:240px;height:30px;" type="text" name="Compare" placeholder="Digite para procurar uma música..." />
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <table id="tblTracks" class="table table-hover infinite-scroll table_sort">
                        <thead>
                            <tr>
                                <th style="cursor:pointer">
                                    Música
                                </th>
                                <th style="cursor:pointer">
                                    Artísta
                                </th>
                                <th style="cursor:pointer">
                                    Album
                                </th>
                                <th class="sort-duration" style="cursor:pointer">
                                    Duração
                                </th>
                            </tr>
                        </thead>
                        <tbody class="navigation_list">
                            @{Html.RenderPartial("PlaylistTracks", @Model.PlaylistTrack);}
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">@Html.Partial("_Loading")</div>
                        <div class="col-md-4"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section scripts{
        <script src="/Scripts/table-sorter.js"></script>
        <script type="text/javascript">
            $(function () {
                $("div#loading").hide();
            });
            var moreRowsUrl = '@Html.Raw(@Url.Action("PlaylistTracks", "PlaylistTracks", new {nextUrl = @Model.PlaylistTrack.Next}))'

            $(window).scroll(scrollHandler);

            $(function () {
                $("table.table_sort").sort_table({
                    "action": "init"
                });
            });

            $(document).ready(function () {
                $('#search-navigation').hideseek({
                    highlight: true,
                    nodata: 'Ops... Nenhum resultado encontrado...',
                    navigation: true
                });
            });

            function embededSpotify(trackId) {
                window.open("https://embed.spotify.com/?uri=spotify:track:" + trackId + '', "newWindow", "height=400, width=300, location=no, menubar=no, status=no, titlebar=no, toolbar=no, resizable=no", true);
            }
        </script>
    }
   
</div>

MMS/MusicMatchSpotifyWeb/Views/PlaylistTracks/PlaylistTracks.cshtml
@model SpotifyWebAPI.Page<SpotifyWebAPI.PlaylistTrack>

@foreach (var item in @Model.Items)
{
    <tr id="trTrackTitle" title="Clique para ouvir!" style="cursor:pointer" onclick="embededSpotify('@item.Track.Id');">
        <td>@item.Track.Name</td>
        <td>@item.Track.Artists.FirstOrDefault().Name</td>
        <td>@item.Track.Album.Name</td>
        <td>
            @{
                //Milis to Min ( duration in ms / 60k )
                TimeSpan t = TimeSpan.FromMilliseconds(item.Track.Duration);
                string answer = string.Format("{0:D2}:{1:D2}", t.Minutes, t.Seconds);
                @answer
            }
        </td>
    </tr>
}

MMS/MusicMatchSpotifyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Music Match Spotify</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/Content/heroic-features.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="/Content/Site.css" rel="stylesheet" />
    <link href="/Content/bootstrap-table.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand menu-logomarca" href="/Home/CallBack">Music Match Spotify</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav menu-font-size">
                    <li>
                        <a href="#">Sobre</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                   
                </ul>
                @RenderSection("header")
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
   
        @RenderBody()
        <hr>
        <!-- Footer -->
        <footer>
            <div class="text-center">
                <div class="col-lg-12">
                    <p>Copyright &copy; Music Match Spotify 2015 - Created by Danilo Cecilia</p>
                </div>
            </div>
        </footer>
    
    <!-- /.container -->
    <!-- jQuery -->
    <script src="/Scripts/jquery-2.1.4.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Scripts/bootstrap.min.js"></script>
    <script src="/Scripts/bootstrap-table.js"></script>
    <script src="/Scripts/infiniteScroll.js"></script>
    <script src="/Scripts/jquery.hideseek.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

MMS/MusicMatchSpotifyWeb/Views/Shared/_Loading.cshtml
<div id="loading">
    <div class="loading-wheel">
        <img width="20" height="20" src="/Content/images/spin.gif">
    </div>
    <div><p><b>Carregando mais músicas...</b></p></div>
</div>

MMS/MusicMatchSpotifyWeb/Views/Shared/_LogoHeader.cshtml
@model SpotifyWebAPI.User
<ul class="nav navbar-nav menu-font-size" style="float:right">
    <li>
        <a href="/Home/Profile" class="navbar-brand ">
            @(Model.DisplayName == null ? Model.Id : Model.DisplayName)
        </a>
    </li>
    <li>
        <div class="header-img">
            <img width="45" class="img-thumbnail" style="padding:1px;" src="@(Model.Images.Count > 0 ? Model.Images[0].Url : "http://www.ala-access.com/s/wp-content/uploads/2016/01/analyst-placeholder-avatar.png")" alt="">
        </div>
    </li>
</ul>